grpc.server.port=59091
logging.level.ru.practicum.telemetry.collector=DEBUG
logging.level.root=INFO

KAFKA_BOOTSTRAP_SERVERS=localhost:9092
KAFKA_TOPIC_NAME_HUBS_EVENTS=telemetry.hubs.v1
KAFKA_TOPIC_NAME_SENSORS_EVENTS=telemetry.sensors.v1