logging.level.ru.practicum.telemetry.aggregator=DEBUG
logging.level.root=INFO

KAFKA_BOOTSTRAP_SERVERS=localhost:9092
KAFKA_CONSUMER_GROUP_ID=aggregator-group
KAFKA_AUTO_OFFSET_RESET_CONFIG=earliest
KAFKA_TELEMETRY_SENSORS_DATA_TOPIC=telemetry.sensors.v1
KAFKA_TELEMETRY_SNAPSHOT_DATA_TOPIC=telemetry.snapshots.v1
