spring:
  main:
    banner-mode: off
    log-startup-info: false

logging:
  level:
    root: INFO
    ru.yandex.practicum.telemetry: WARN
    org:
      springframework: ERROR
      apache.kafka: WARN

kafka:
  bootstrap-servers: "localhost:9092"
  auto-offset-reset: earliest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/